services:
  db:
    container_name: postgres_database
    image: postgres:15.10-alpine3.20
    restart: always
    ports:
      - "5432:5432"
    volumes: 
      - psql-vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=school_api 

  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:8.14.0
    volumes:
      - pgadmin-vol:/var/lib/pgadmin
    ports:
      - "80:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@mail.co
      - PGADMIN_DEFAULT_PASSWORD=pgadmin456

volumes:
  psql-vol:
  pgadmin-vol:
  
